#!/bin/bash

if [ ! -z $1 ]; then
  export psacsrc="${1}/target/PeyangSuperbAntiCheat-0.2.1.jar"
else
  read -rp "Repository Root:" reporoot
  export psacsrc="${reporoot}/target/PeyangSuperbAntiCheat-0.2.1.jar"
fi

if [ ! -z $2 ]; then
  export psacdist=${2}
else
  read -rp "Plugin install dir(Auto create directory):" ans
  export psacdist="${ans}/PSAC.jar"
fi

echo "${psacsrc} -> ${psacdist}"

if [ $(uname) = Darwin ]; then
  install -m755 ${psacsrc} ${psacdist} && echo "SUCCESS: PeyangSuperbAntiCheat Successfly Installed."
else
  install -Dm755 ${psacsrc} ${psacdist} && echo "SUCCESS: PeyangSuperbAntiCheat Successfly Installed."
fi
