#Spigot(Bukkit)側と同じ設定をしてください。
#データベースのパス
#相対パスが利用できます。
database:
  #メソッド。sqliteなら org.sqlite.JDBC Mysqlなら com.mysql.jdbc.Driver
  method: "org.sqlite.JDBC"
  url: "jdbc:sqlite:"

  logPath: "./log.db"