#データベースのパス
#相対パスが利用できます。
database:
  path: "./eye.db"
  logPath: "./log.db"
  learnPath: "./learn.json"
  trustPath: "./trust.db"

#npc関係のコンフィグです。
npc:
  #指定された秒数、NPCを召喚します。
  #秒数が短いとその中でのVL評価を行います。
  seconds: 5

  #NPCの速度などを変えるとき、微調整してください。
  #別の値に指定する場合、適切な値でないとIssue 17に対応できなくなる可能性があります。
  time: 0.3

  #NPCのプレイヤーからの半径を指定します。
  #この値が最も安定している値ですが、ハッククライアントによってはKillAuraの半径を変更している場合もあります。
  range: 2.1
  #NPC召喚に"-r"引数を付けた場合のプレイヤーからの半径を指定します。
  #これはサバイバルモードの最大攻撃半径に0.1を足した値がデフォルトであり、Reachハックを使用しているかどうか確認することができます。
  reachRange: 4.6

  #NPCがWaveを描くかどうかを指定します。
  #falseにした場合、NPCはWaveを描かなくなりIssue 17に対応できなくなります。
  wave: true

  #Waveの最小単位を指定します。
  #小さいほど動作が大きくなります。
  waveMin: 0.3

  #Panic NPCのプレイヤーからの半径を指定します。
  #Panic NPCの場合、通常のNPCと異なり半径が大きいとうまく動作しない可能性があります。
  panicRange: 1.5
  #NPC召喚に"-r"引数を付けた場合のプレイヤーからの半径を指定します。
  #これはサバイバルモードの最大攻撃半径に0.1を足した値がデフォルトであり、Reachハックを使用しているかどうか確認することができます。
  reachPanicRange: 4.6

  kill: 3

  #NPCの学習係数を指定します。
  #大きいほどニューラルネットワークでの処理の回数が少なくなりますが、精度は低くなります。サーバースペックに合わせて適切な値に変更してください。
  #Doubleのため小数第一位以降も設定可能です。
  learn: 0.3

  #NPCがlearncountより学習出来ていない場合にこの値を利用してVLを評価します。
  #VLがこの値より大きかった場合にキックされます。
  vlLevel: 17

  #学習機能がこの回数以上学習した場合にkickの評価を学習機能に譲渡します。
  #適切な値に変更してください。
  learncount: 15

  speed:
    wave: true
    waveRange: 0.03

mod:
  tracking:
    ##有効/無効
    enabled: true
    #CompassTracker3000™のトラックチックです。
    trackTicks: 10

kick:
  #キックまでの遅延です。
  #リアルにするなら、2(sec)が最強です。
  delay: 2
  #Kickまでのデータが見つからない場合のデフォルト値
  defaultKick: 25

decoration:
  #キックされた瞬間に雷落とすかどうか
  lighting: true
  #ブレイズのやつやるかどうか
  flame: true
  #魔法陣の表示
  circle: true

  #レーザー表示
  laser: true

message:
  #プレイヤーがレポートを提出した時などのメッセージを
  #「Lynx」Modと互換性をもたせます。
  lynx: true

autoMessage:
  #定期メッセージの有効/無効です
  enabled: true
  #定期メッセージの周期です。(分指定)
  #0にすると、自動で1になりますが、ぶっ壊れるので注意です。
  time: 15

commands:
  override:
    #kickコマンドのオーバーライド
    kick:
      enable: true
    ban:
      enable: true