# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI with Ant (stable)

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
    - name: Install
      run: mkdir -p ${GITHUB_WORKSPACE}/ins && bash ${GITHUB_WORKSPACE}/install ${GITHUB_WORKSPACE} ${GITHUB_WORKSPACE}/ins

  build-macos:

    runs-on: macos-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
    - name: Install
      run: mkdir -p ${GITHUB_WORKSPACE}/ins && bash ${GITHUB_WORKSPACE}/install ${GITHUB_WORKSPACE} ${GITHUB_WORKSPACE}/ins
